---
- name: Pull docker image
  hosts: all
  tasks:
    - name: Pull image of working project from dockerhub
      docker_image:
        name: tusharsnagpal/scientific_cal
        tag: latest
        source: pull
#    - name: Create & Start Calculator Docker Container
#      docker_container:
#        name: spe-mini-proj
#        image: tusharsnagpal/scientific_cal
#        state: started
#        tty: yes
#        interactive: yes
