---
- name: Pull docker image
  hosts: localhost
  tasks:
    - name: Pull image of working project from dockerhub
      docker_image:
        name: tusharsnagpal/spe-mini-proj:latest
        source: pull
