---
- name: Pull docker image
  hosts: all
  tasks:
    - name: IMAGE PULL FROM DOCKER HUB
      docker_image:
        name: tusharsnagpal/scientific_cal
        tag: latest
        source: pull
    - name: DOCKER CREATE
      docker_container:
        name: spe-mini-proj
        image: tusharsnagpal/scientific_cal
        state: started
        tty: yes
        interactive: yes