---
- name: Pull docker image
  hosts: localhost
  tasks:
    - name: Pull image of working project from dockerhub
      docker_image:
        name: tusharsnagpal/spe-mini-proj
        tag: latest
        source: pull
    - name: Create & Start Calculator Docker Container
      docker_container:
        name: spe-mini-proj
        image: tusharsnagpal/spe-mini-proj
        state: started
        tty: yes
        interactive: yes
